export const formConfig = {
  risks: [
    {
      name: "frequency",
      label: "Frecuencia",
      type: "number",
      placeholder: "Frecuencia con la que ocurre  el  riesgo",
      required: true,
    },
    {
      name: "penalty",
      label: "Penalización",
      type: "number",
      placeholder: "Penalización del riesgo",
      required: true,
    },
    {
      name: "control_type",
      label: "Tipo de control",
      type: "select",
      staticOptions: [
        { id: 1, name: "Preventivo" },
        { id: 2, name: "Detectivo" },
        { id: 3, name: "Correctivo" },
      ]
    },
    {
      name: "implementation",
      label: "Implementación",
      type: "select",
      staticOptions: [
        { id: 1, name: "Manual" },
        { id: 2, name: "Automatico" },
      ],
    },
    {
      name: "threat_id",
      label: "Amenaza",
      type: "select",
      options: "threats",
      required: true,
    },
    {
      name: "vulnerability_id",
      label: "Vulnerabilidad",
      type: "select",
      options: "vulnerabilities",
      required: true,
    },
    {
      name: "risk_type_id",
      label: "Tipo de riesgo",
      type: "select",
      options: "riskTypes",
      required: true,
    },
    {
      name: "asset_type_id",
      label: "Tipo de activo",
      type: "select",
      options: "assetTypes",
      required: true,
    },
  ],

  assets: [
    {
      name: "process",
      label: "Proceso",
      type: "text",
      placeholder: "Ingrese el proceso",
      required: true,
    },
    {
      name: "name",
      label: "Nombre",
      type: "text",
      placeholder: "Ingrese el nombre del activo",
      required: true,
    },
    {
      name: "description",
      label: "Descripción",
      type: "text",
      placeholder: "Descripción del activo",
      required: true,
    },
    {
      name: "asset_type_id",
      label: "Tipo de activo",
      type: "select",
      options: "assetTypes",
      required: true,
    },
    {
      name: "format",
      label: "Formato",
      type: "text",
      placeholder: "Ingrese el formato del activo",
      required: true,
    },
    {
      name: "software_version",
      label: "Versión del software",
      type: "text",
      placeholder: "Ingrese la versión del software",
      required: true,
    },
    {
      name: "manufacturer",
      label: "Fabricante",
      type: "text",
      placeholder: "Ingrese el fabricante",
      required: true,
    },
    {
      name: "physical_location",
      label: "Ubicación Física",
      type: "text",
      placeholder: "Ingrese la ubicación física",
      required: true,
    },
    {
      name: "electronic_location",
      label: "Ubicación Electrónica",
      type: "text",
      placeholder: "Ingrese la ubicación electrónica",
      required: true,
    },
    {
      name: "responsible",
      label: "Responsable",
      type: "text",
      placeholder: "Ingrese el nombre del responsable",
      required: true,
    },
    {
      name: "user_access",
      label: "Acceso de Usuario",
      type: "text",
      placeholder: "Ingrese el acceso de usuario",
      required: true,
    },
    {
      name: "access_date",
      label: "Fecha de Acceso",
      type: "datetime-local",
      required: true,
    },
    {
      name: "state",
      label: "Estado",
      type: "boolean", // Este campo será manejado como un checkbox
      values: ["Activo", "Inactivo"],
      required: true,
    },
    {
      name: "entry_date",
      label: "Fecha de Entrada",
      type: "datetime-local",
      required: true,
    },
    {
      name: "retirement_date",
      label: "Fecha de Retiro",
      type: "datetime-local",
      required: true,
    },
    {
      name: "availability",
      label: "Disponibilidad",
      type: "boolean", // Este campo también será manejado como un checkbox
      values: ["Disponible", "No disponible"],
      required: true,
    },
    {
      name: "integrity",
      label: "Integridad",
      type: "text",
      placeholder: "Ingrese la integridad del activo",
      required: true,
    },
    {
      name: "criticality",
      label: "Criticidad",
      type: "text",
      placeholder: "Ingrese la criticidad del activo",
      required: true,
    },
    {
      name: "confidentiality",
      label: "Confidencialidad",
      type: "text",
      placeholder: "Ingrese la confidencialidad del activo",
      required: true,
    },
  ],
  threats:[{
    name: "name",
    label: "Nombre",
    type: "text",
    placeholder: "Ingresa un nombre",
    required: true,
  },
  {
    name: "description",
    label: "Descripción",
    type: "text",
    placeholder: "Ingresa una descripeción",
    required: true,
  }]
};
